#!/usr/bin/env bash
# uploads a file to a server
#                               $1       $2    $3          $4
msg="Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
# Ubuntu@196.0.0.1~ -> $3@$2~
# User@IP

if [ "$4" ]; then
   scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~"
elif [ "$3" ]; then
    # no provided ssh key 
    scp -o StrictHostKeyChecking=no "$1" "$3@$2~"
else
	echo "$msg";
fi