#!/usr/bin/env bash
# Displays the time for 12 horus and 59 minutes.

hour=0

while [ $hour -ne 13 ]
do
  echo "Hour: $hour"
  minute=1
  while [ $minute -ne 60 ]
  do
    echo "$minute"
    (( minute++ ))
  done
  (( hour++ ))
done
